[news]
title = "Billboard Korea ─ NEWS"
url = "http://billboard.co.kr/main/news/list"
entrySelector = "ul.clr.news li"
titleSelector = "div.txt span"
linkSelector = "a"
imageSelector = "div.img-con img"
contentSelector = "div[class='txt'] span"
waitUntil = "networkidle"

[video]
title = "Billboard Korea ─ VIDEO"
url = "http://billboard.co.kr/main/videos/list"
entrySelector = "ul.clr.news li"
titleSelector = "div.txt span"
linkSelector = "a"
imageSelector = "div.img-con img"
contentSelector = "div[class='txt'] span"
waitUntil = "networkidle"
